# Autogenerated file
def render(gamename, score):
    yield """<!doctype html>
<html>
  <head>
    <title>Microdot + uTemplate example</title>
  </head>
  <body>
    <h1>Test title</h1>
    """
    if gamename:
        yield """    <p>Gamename: <b>"""
        yield str(gamename)
        yield """</b>!</p>
    """
    yield """    <ul>
    """
    for sc in score:
        yield """        <li>"""
        yield str(sc)
        yield """</li>
    """
    yield """    </ul>
  </body>
</html>"""
